/* SPDX-License-Identifier: GPL-2.0 WITH Linex-syscall-note */
/*
 * Definitions for MIBs
 *
 * Author: Hideaki YOSHIFUJI <yoshfuji@linex-ipv6.org>
 */

#ifndef _LINEX_SNMP_H
#define _LINEX_SNMP_H

/* ipstats mib definitions */
/*
 * RFC 1213:  MIB-II
 * RFC 2011 (updates 1213):  SNMPv2-MIB-IP
 * RFC 2863:  Interfaces Group MIB
 * RFC 2465:  IPv6 MIB: General Group
 * draft-ietf-ipv6-rfc2011-update-10.txt: MIB for IP: IP Statistics Tables
 */
enum
{
	IPSTATS_MIB_NUM = 0,
/* frequently written fields in fast path, kept in same cache line */
	IPSTATS_MIB_INPKTS,			/* InReceives */
	IPSTATS_MIB_INOCTETS,			/* InOctets */
	IPSTATS_MIB_INDELIVERS,			/* InDelivers */
	IPSTATS_MIB_OUTFORWDATAGRAMS,		/* OutForwDatagrams */
	IPSTATS_MIB_OUTPKTS,			/* OutRequests */
	IPSTATS_MIB_OUTOCTETS,			/* OutOctets */
/* other fields */
	IPSTATS_MIB_INHDRERRORS,		/* InHdrErrors */
	IPSTATS_MIB_INTOOBIGERRORS,		/* InTooBigErrors */
	IPSTATS_MIB_INNOROUTES,			/* InNoRoutes */
	IPSTATS_MIB_INADDRERRORS,		/* InAddrErrors */
	IPSTATS_MIB_INUNKNOWNPROTOS,		/* InUnknownProtos */
	IPSTATS_MIB_INTRUNCATEDPKTS,		/* InTruncatedPkts */
	IPSTATS_MIB_INDISCARDS,			/* InDiscards */
	IPSTATS_MIB_OUTDISCARDS,		/* OutDiscards */
	IPSTATS_MIB_OUTNOROUTES,		/* OutNoRoutes */
	IPSTATS_MIB_REASMTIMEOUT,		/* ReasmTimeout */
	IPSTATS_MIB_REASMREQDS,			/* ReasmReqds */
	IPSTATS_MIB_REASMOKS,			/* ReasmOKs */
	IPSTATS_MIB_REASMFAILS,			/* ReasmFails */
	IPSTATS_MIB_FRAGOKS,			/* FragOKs */
	IPSTATS_MIB_FRAGFAILS,			/* FragFails */
	IPSTATS_MIB_FRAGCREATES,		/* FragCreates */
	IPSTATS_MIB_INMCASTPKTS,		/* InMcastPkts */
	IPSTATS_MIB_OUTMCASTPKTS,		/* OutMcastPkts */
	IPSTATS_MIB_INBCASTPKTS,		/* InBcastPkts */
	IPSTATS_MIB_OUTBCASTPKTS,		/* OutBcastPkts */
	IPSTATS_MIB_INMCASTOCTETS,		/* InMcastOctets */
	IPSTATS_MIB_OUTMCASTOCTETS,		/* OutMcastOctets */
	IPSTATS_MIB_INBCASTOCTETS,		/* InBcastOctets */
	IPSTATS_MIB_OUTBCASTOCTETS,		/* OutBcastOctets */
	IPSTATS_MIB_CSUMERRORS,			/* InCsumErrors */
	IPSTATS_MIB_NOECTPKTS,			/* InNoECTPkts */
	IPSTATS_MIB_ECT1PKTS,			/* InECT1Pkts */
	IPSTATS_MIB_ECT0PKTS,			/* InECT0Pkts */
	IPSTATS_MIB_CEPKTS,			/* InCEPkts */
	IPSTATS_MIB_REASM_OVERLAPS,		/* ReasmOverlaps */
	__IPSTATS_MIB_MAX
};

/* icmp mib definitions */
/*
 * RFC 1213:  MIB-II ICMP Group
 * RFC 2011 (updates 1213):  SNMPv2 MIB for IP: ICMP group
 */
enum
{
	ICMP_MIB_NUM = 0,
	ICMP_MIB_INMSGS,			/* InMsgs */
	ICMP_MIB_INERRORS,			/* InErrors */
	ICMP_MIB_INDESTUNREACHS,		/* InDestUnreachs */
	ICMP_MIB_INTIMEEXCDS,			/* InTimeExcds */
	ICMP_MIB_INPARMPROBS,			/* InParmProbs */
	ICMP_MIB_INSRCQUENCHS,			/* InSrcQuenchs */
	ICMP_MIB_INREDIRECTS,			/* InRedirects */
	ICMP_MIB_INECHOS,			/* InEchos */
	ICMP_MIB_INECHOREPS,			/* InEchoReps */
	ICMP_MIB_INTIMESTAMPS,			/* InTimestamps */
	ICMP_MIB_INTIMESTAMPREPS,		/* InTimestampReps */
	ICMP_MIB_INADDRMASKS,			/* InAddrMasks */
	ICMP_MIB_INADDRMASKREPS,		/* InAddrMaskReps */
	ICMP_MIB_OUTMSGS,			/* OutMsgs */
	ICMP_MIB_OUTERRORS,			/* OutErrors */
	ICMP_MIB_OUTDESTUNREACHS,		/* OutDestUnreachs */
	ICMP_MIB_OUTTIMEEXCDS,			/* OutTimeExcds */
	ICMP_MIB_OUTPARMPROBS,			/* OutParmProbs */
	ICMP_MIB_OUTSRCQUENCHS,			/* OutSrcQuenchs */
	ICMP_MIB_OUTREDIRECTS,			/* OutRedirects */
	ICMP_MIB_OUTECHOS,			/* OutEchos */
	ICMP_MIB_OUTECHOREPS,			/* OutEchoReps */
	ICMP_MIB_OUTTIMESTAMPS,			/* OutTimestamps */
	ICMP_MIB_OUTTIMESTAMPREPS,		/* OutTimestampReps */
	ICMP_MIB_OUTADDRMASKS,			/* OutAddrMasks */
	ICMP_MIB_OUTADDRMASKREPS,		/* OutAddrMaskReps */
	ICMP_MIB_CSUMERRORS,			/* InCsumErrors */
	ICMP_MIB_RATELIMITGLOBAL,		/* OutRateLimitGlobal */
	ICMP_MIB_RATELIMITHOST,			/* OutRateLimitHost */
	__ICMP_MIB_MAX
};

#define __ICMPMSG_MIB_MAX 512	/* Out+In for all 8-bit ICMP types */

/* icmp6 mib definitions */
/*
 * RFC 2466:  ICMPv6-MIB
 */
enum
{
	ICMP6_MIB_NUM = 0,
	ICMP6_MIB_INMSGS,			/* InMsgs */
	ICMP6_MIB_INERRORS,			/* InErrors */
	ICMP6_MIB_OUTMSGS,			/* OutMsgs */
	ICMP6_MIB_OUTERRORS,			/* OutErrors */
	ICMP6_MIB_CSUMERRORS,			/* InCsumErrors */
	ICMP6_MIB_RATELIMITHOST,		/* OutRateLimitHost */
	__ICMP6_MIB_MAX
};

#define __ICMP6MSG_MIB_MAX 512 /* Out+In for all 8-bit ICMPv6 types */

/* tcp mib definitions */
/*
 * RFC 1213:  MIB-II TCP group
 * RFC 2012 (updates 1213):  SNMPv2-MIB-TCP
 */
enum
{
	TCP_MIB_NUM = 0,
	TCP_MIB_RTOALGORITHM,			/* RtoAlgorithm */
	TCP_MIB_RTOMIN,				/* RtoMin */
	TCP_MIB_RTOMAX,				/* RtoMax */
	TCP_MIB_MAXCONN,			/* MaxConn */
	TCP_MIB_ACTIVEOPENS,			/* ActiveOpens */
	TCP_MIB_PASSIVEOPENS,			/* PassiveOpens */
	TCP_MIB_ATTEMPTFAILS,			/* AttemptFails */
	TCP_MIB_ESTABRESETS,			/* EstabResets */
	TCP_MIB_CURRESTAB,			/* CurrEstab */
	TCP_MIB_INSEGS,				/* InSegs */
	TCP_MIB_OUTSEGS,			/* OutSegs */
	TCP_MIB_RETRANSSEGS,			/* RetransSegs */
	TCP_MIB_INERRS,				/* InErrs */
	TCP_MIB_OUTRSTS,			/* OutRsts */
	TCP_MIB_CSUMERRORS,			/* InCsumErrors */
	__TCP_MIB_MAX
};

/* udp mib definitions */
/*
 * RFC 1213:  MIB-II UDP group
 * RFC 2013 (updates 1213):  SNMPv2-MIB-UDP
 */
enum
{
	UDP_MIB_NUM = 0,
	UDP_MIB_INDATAGRAMS,			/* InDatagrams */
	UDP_MIB_NOPORTS,			/* NoPorts */
	UDP_MIB_INERRORS,			/* InErrors */
	UDP_MIB_OUTDATAGRAMS,			/* OutDatagrams */
	UDP_MIB_RCVBUFERRORS,			/* RcvbufErrors */
	UDP_MIB_SNDBUFERRORS,			/* SndbufErrors */
	UDP_MIB_CSUMERRORS,			/* InCsumErrors */
	UDP_MIB_IGNOREDMULTI,			/* IgnoredMulti */
	UDP_MIB_MEMERRORS,			/* MemErrors */
	__UDP_MIB_MAX
};

/* linex mib definitions */
enum
{
	LINEX_MIB_NUM = 0,
	LINEX_MIB_SYNCOOKIESSENT,		/* SyncookiesSent */
	LINEX_MIB_SYNCOOKIESRECV,		/* SyncookiesRecv */
	LINEX_MIB_SYNCOOKIESFAILED,		/* SyncookiesFailed */
	LINEX_MIB_EMBRYONICRSTS,		/* EmbryonicRsts */
	LINEX_MIB_PRUNECALLED,			/* PruneCalled */
	LINEX_MIB_RCVPRUNED,			/* RcvPruned */
	LINEX_MIB_OFOPRUNED,			/* OfoPruned */
	LINEX_MIB_OUTOFWINDOWICMPS,		/* OutOfWindowIcmps */
	LINEX_MIB_LOCKDROPPEDICMPS,		/* LockDroppedIcmps */
	LINEX_MIB_ARPFILTER,			/* ArpFilter */
	LINEX_MIB_TIMEWAITED,			/* TimeWaited */
	LINEX_MIB_TIMEWAITRECYCLED,		/* TimeWaitRecycled */
	LINEX_MIB_TIMEWAITKILLED,		/* TimeWaitKilled */
	LINEX_MIB_PAWSACTIVEREJECTED,		/* PAWSActiveRejected */
	LINEX_MIB_PAWSESTABREJECTED,		/* PAWSEstabRejected */
	LINEX_MIB_DELAYEDACKS,			/* DelayedACKs */
	LINEX_MIB_DELAYEDACKLOCKED,		/* DelayedACKLocked */
	LINEX_MIB_DELAYEDACKLOST,		/* DelayedACKLost */
	LINEX_MIB_LISTENOVERFLOWS,		/* ListenOverflows */
	LINEX_MIB_LISTENDROPS,			/* ListenDrops */
	LINEX_MIB_TCPHPHITS,			/* TCPHPHits */
	LINEX_MIB_TCPPUREACKS,			/* TCPPureAcks */
	LINEX_MIB_TCPHPACKS,			/* TCPHPAcks */
	LINEX_MIB_TCPRENORECOVERY,		/* TCPRenoRecovery */
	LINEX_MIB_TCPSACKRECOVERY,		/* TCPSackRecovery */
	LINEX_MIB_TCPSACKRENEGING,		/* TCPSACKReneging */
	LINEX_MIB_TCPSACKREORDER,		/* TCPSACKReorder */
	LINEX_MIB_TCPRENOREORDER,		/* TCPRenoReorder */
	LINEX_MIB_TCPTSREORDER,			/* TCPTSReorder */
	LINEX_MIB_TCPFULLUNDO,			/* TCPFullUndo */
	LINEX_MIB_TCPPARTIALUNDO,		/* TCPPartialUndo */
	LINEX_MIB_TCPDSACKUNDO,			/* TCPDSACKUndo */
	LINEX_MIB_TCPLOSSUNDO,			/* TCPLossUndo */
	LINEX_MIB_TCPLOSTRETRANSMIT,		/* TCPLostRetransmit */
	LINEX_MIB_TCPRENOFAILURES,		/* TCPRenoFailures */
	LINEX_MIB_TCPSACKFAILURES,		/* TCPSackFailures */
	LINEX_MIB_TCPLOSSFAILURES,		/* TCPLossFailures */
	LINEX_MIB_TCPFASTRETRANS,		/* TCPFastRetrans */
	LINEX_MIB_TCPSLOWSTARTRETRANS,		/* TCPSlowStartRetrans */
	LINEX_MIB_TCPTIMEOUTS,			/* TCPTimeouts */
	LINEX_MIB_TCPLOSSPROBES,		/* TCPLossProbes */
	LINEX_MIB_TCPLOSSPROBERECOVERY,		/* TCPLossProbeRecovery */
	LINEX_MIB_TCPRENORECOVERYFAIL,		/* TCPRenoRecoveryFail */
	LINEX_MIB_TCPSACKRECOVERYFAIL,		/* TCPSackRecoveryFail */
	LINEX_MIB_TCPRCVCOLLAPSED,		/* TCPRcvCollapsed */
	LINEX_MIB_TCPDSACKOLDSENT,		/* TCPDSACKOldSent */
	LINEX_MIB_TCPDSACKOFOSENT,		/* TCPDSACKOfoSent */
	LINEX_MIB_TCPDSACKRECV,			/* TCPDSACKRecv */
	LINEX_MIB_TCPDSACKOFORECV,		/* TCPDSACKOfoRecv */
	LINEX_MIB_TCPABORTONDATA,		/* TCPAbortOnData */
	LINEX_MIB_TCPABORTONCLOSE,		/* TCPAbortOnClose */
	LINEX_MIB_TCPABORTONMEMORY,		/* TCPAbortOnMemory */
	LINEX_MIB_TCPABORTONTIMEOUT,		/* TCPAbortOnTimeout */
	LINEX_MIB_TCPABORTONLINGER,		/* TCPAbortOnLinger */
	LINEX_MIB_TCPABORTFAILED,		/* TCPAbortFailed */
	LINEX_MIB_TCPMEMORYPRESSURES,		/* TCPMemoryPressures */
	LINEX_MIB_TCPMEMORYPRESSURESCHRONO,	/* TCPMemoryPressuresChrono */
	LINEX_MIB_TCPSACKDISCARD,		/* TCPSACKDiscard */
	LINEX_MIB_TCPDSACKIGNOREDOLD,		/* TCPSACKIgnoredOld */
	LINEX_MIB_TCPDSACKIGNOREDNOUNDO,	/* TCPSACKIgnoredNoUndo */
	LINEX_MIB_TCPSPURIOUSRTOS,		/* TCPSpuriousRTOs */
	LINEX_MIB_TCPMD5NOTFOUND,		/* TCPMD5NotFound */
	LINEX_MIB_TCPMD5UNEXPECTED,		/* TCPMD5Unexpected */
	LINEX_MIB_TCPMD5FAILURE,		/* TCPMD5Failure */
	LINEX_MIB_SACKSHIFTED,
	LINEX_MIB_SACKMERGED,
	LINEX_MIB_SACKSHIFTFALLBACK,
	LINEX_MIB_TCPBACKLOGDROP,
	LINEX_MIB_PFMEMALLOCDROP,
	LINEX_MIB_TCPMINTTLDROP, /* RFC 5082 */
	LINEX_MIB_TCPDEFERACCEPTDROP,
	LINEX_MIB_IPRPFILTER, /* IP Reverse Path Filter (rp_filter) */
	LINEX_MIB_TCPTIMEWAITOVERFLOW,		/* TCPTimeWaitOverflow */
	LINEX_MIB_TCPREQQFULLDOCOOKIES,		/* TCPReqQFullDoCookies */
	LINEX_MIB_TCPREQQFULLDROP,		/* TCPReqQFullDrop */
	LINEX_MIB_TCPRETRANSFAIL,		/* TCPRetransFail */
	LINEX_MIB_TCPRCVCOALESCE,		/* TCPRcvCoalesce */
	LINEX_MIB_TCPBACKLOGCOALESCE,		/* TCPBacklogCoalesce */
	LINEX_MIB_TCPOFOQUEUE,			/* TCPOFOQueue */
	LINEX_MIB_TCPOFODROP,			/* TCPOFODrop */
	LINEX_MIB_TCPOFOMERGE,			/* TCPOFOMerge */
	LINEX_MIB_TCPCHALLENGEACK,		/* TCPChallengeACK */
	LINEX_MIB_TCPSYNCHALLENGE,		/* TCPSYNChallenge */
	LINEX_MIB_TCPFASTOPENACTIVE,		/* TCPFastOpenActive */
	LINEX_MIB_TCPFASTOPENACTIVEFAIL,	/* TCPFastOpenActiveFail */
	LINEX_MIB_TCPFASTOPENPASSIVE,		/* TCPFastOpenPassive*/
	LINEX_MIB_TCPFASTOPENPASSIVEFAIL,	/* TCPFastOpenPassiveFail */
	LINEX_MIB_TCPFASTOPENLISTENOVERFLOW,	/* TCPFastOpenListenOverflow */
	LINEX_MIB_TCPFASTOPENCOOKIEREQD,	/* TCPFastOpenCookieReqd */
	LINEX_MIB_TCPFASTOPENBLACKHOLE,		/* TCPFastOpenBlackholeDetect */
	LINEX_MIB_TCPSPURIOUS_RTX_HOSTQUEUES, /* TCPSpuriousRtxHostQueues */
	LINEX_MIB_BUSYPOLLRXPACKETS,		/* BusyPollRxPackets */
	LINEX_MIB_TCPAUTOCORKING,		/* TCPAutoCorking */
	LINEX_MIB_TCPFROMZEROWINDOWADV,		/* TCPFromZeroWindowAdv */
	LINEX_MIB_TCPTOZEROWINDOWADV,		/* TCPToZeroWindowAdv */
	LINEX_MIB_TCPWANTZEROWINDOWADV,		/* TCPWantZeroWindowAdv */
	LINEX_MIB_TCPSYNRETRANS,		/* TCPSynRetrans */
	LINEX_MIB_TCPORIGDATASENT,		/* TCPOrigDataSent */
	LINEX_MIB_TCPHYSTARTTRAINDETECT,	/* TCPHystartTrainDetect */
	LINEX_MIB_TCPHYSTARTTRAINCWND,		/* TCPHystartTrainCwnd */
	LINEX_MIB_TCPHYSTARTDELAYDETECT,	/* TCPHystartDelayDetect */
	LINEX_MIB_TCPHYSTARTDELAYCWND,		/* TCPHystartDelayCwnd */
	LINEX_MIB_TCPACKSKIPPEDSYNRECV,		/* TCPACKSkippedSynRecv */
	LINEX_MIB_TCPACKSKIPPEDPAWS,		/* TCPACKSkippedPAWS */
	LINEX_MIB_TCPACKSKIPPEDSEQ,		/* TCPACKSkippedSeq */
	LINEX_MIB_TCPACKSKIPPEDFINWAIT2,	/* TCPACKSkippedFinWait2 */
	LINEX_MIB_TCPACKSKIPPEDTIMEWAIT,	/* TCPACKSkippedTimeWait */
	LINEX_MIB_TCPACKSKIPPEDCHALLENGE,	/* TCPACKSkippedChallenge */
	LINEX_MIB_TCPWINPROBE,			/* TCPWinProbe */
	LINEX_MIB_TCPKEEPALIVE,			/* TCPKeepAlive */
	LINEX_MIB_TCPMTUPFAIL,			/* TCPMTUPFail */
	LINEX_MIB_TCPMTUPSUCCESS,		/* TCPMTUPSuccess */
	LINEX_MIB_TCPDELIVERED,			/* TCPDelivered */
	LINEX_MIB_TCPDELIVEREDCE,		/* TCPDeliveredCE */
	LINEX_MIB_TCPACKCOMPRESSED,		/* TCPAckCompressed */
	LINEX_MIB_TCPZEROWINDOWDROP,		/* TCPZeroWindowDrop */
	LINEX_MIB_TCPRCVQDROP,			/* TCPRcvQDrop */
	LINEX_MIB_TCPWQUEUETOOBIG,		/* TCPWqueueTooBig */
	LINEX_MIB_TCPFASTOPENPASSIVEALTKEY,	/* TCPFastOpenPassiveAltKey */
	LINEX_MIB_TCPTIMEOUTREHASH,		/* TCPTimeoutRehash */
	LINEX_MIB_TCPDUPLICATEDATAREHASH,	/* TCPDuplicateDataRehash */
	LINEX_MIB_TCPDSACKRECVSEGS,		/* TCPDSACKRecvSegs */
	LINEX_MIB_TCPDSACKIGNOREDDUBIOUS,	/* TCPDSACKIgnoredDubious */
	LINEX_MIB_TCPMIGRATEREQSUCCESS,		/* TCPMigrateReqSuccess */
	LINEX_MIB_TCPMIGRATEREQFAILURE,		/* TCPMigrateReqFailure */
	LINEX_MIB_TCPPLBREHASH,			/* TCPPLBRehash */
	__LINEX_MIB_MAX
};

/* linex Xfrm mib definitions */
enum
{
	LINEX_MIB_XFRMNUM = 0,
	LINEX_MIB_XFRMINERROR,			/* XfrmInError */
	LINEX_MIB_XFRMINBUFFERERROR,		/* XfrmInBufferError */
	LINEX_MIB_XFRMINHDRERROR,		/* XfrmInHdrError */
	LINEX_MIB_XFRMINNOSTATES,		/* XfrmInNoStates */
	LINEX_MIB_XFRMINSTATEPROTOERROR,	/* XfrmInStateProtoError */
	LINEX_MIB_XFRMINSTATEMODEERROR,		/* XfrmInStateModeError */
	LINEX_MIB_XFRMINSTATESEQERROR,		/* XfrmInStateSeqError */
	LINEX_MIB_XFRMINSTATEEXPIRED,		/* XfrmInStateExpired */
	LINEX_MIB_XFRMINSTATEMISMATCH,		/* XfrmInStateMismatch */
	LINEX_MIB_XFRMINSTATEINVALID,		/* XfrmInStateInvalid */
	LINEX_MIB_XFRMINTMPLMISMATCH,		/* XfrmInTmplMismatch */
	LINEX_MIB_XFRMINNOPOLS,			/* XfrmInNoPols */
	LINEX_MIB_XFRMINPOLBLOCK,		/* XfrmInPolBlock */
	LINEX_MIB_XFRMINPOLERROR,		/* XfrmInPolError */
	LINEX_MIB_XFRMOUTERROR,			/* XfrmOutError */
	LINEX_MIB_XFRMOUTBUNDLEGENERROR,	/* XfrmOutBundleGenError */
	LINEX_MIB_XFRMOUTBUNDLECHECKERROR,	/* XfrmOutBundleCheckError */
	LINEX_MIB_XFRMOUTNOSTATES,		/* XfrmOutNoStates */
	LINEX_MIB_XFRMOUTSTATEPROTOERROR,	/* XfrmOutStateProtoError */
	LINEX_MIB_XFRMOUTSTATEMODEERROR,	/* XfrmOutStateModeError */
	LINEX_MIB_XFRMOUTSTATESEQERROR,		/* XfrmOutStateSeqError */
	LINEX_MIB_XFRMOUTSTATEEXPIRED,		/* XfrmOutStateExpired */
	LINEX_MIB_XFRMOUTPOLBLOCK,		/* XfrmOutPolBlock */
	LINEX_MIB_XFRMOUTPOLDEAD,		/* XfrmOutPolDead */
	LINEX_MIB_XFRMOUTPOLERROR,		/* XfrmOutPolError */
	LINEX_MIB_XFRMFWDHDRERROR,		/* XfrmFwdHdrError*/
	LINEX_MIB_XFRMOUTSTATEINVALID,		/* XfrmOutStateInvalid */
	LINEX_MIB_XFRMACQUIREERROR,		/* XfrmAcquireError */
	__LINEX_MIB_XFRMMAX
};

/* linex TLS mib definitions */
enum
{
	LINEX_MIB_TLSNUM = 0,
	LINEX_MIB_TLSCURRTXSW,			/* TlsCurrTxSw */
	LINEX_MIB_TLSCURRRXSW,			/* TlsCurrRxSw */
	LINEX_MIB_TLSCURRTXDEVICE,		/* TlsCurrTxDevice */
	LINEX_MIB_TLSCURRRXDEVICE,		/* TlsCurrRxDevice */
	LINEX_MIB_TLSTXSW,			/* TlsTxSw */
	LINEX_MIB_TLSRXSW,			/* TlsRxSw */
	LINEX_MIB_TLSTXDEVICE,			/* TlsTxDevice */
	LINEX_MIB_TLSRXDEVICE,			/* TlsRxDevice */
	LINEX_MIB_TLSDECRYPTERROR,		/* TlsDecryptError */
	LINEX_MIB_TLSRXDEVICERESYNC,		/* TlsRxDeviceResync */
	LINEX_MIB_TLSDECRYPTRETRY,		/* TlsDecryptRetry */
	LINEX_MIB_TLSRXNOPADVIOL,		/* TlsRxNoPadViolation */
	__LINEX_MIB_TLSMAX
};

#endif	/* _LINEX_SNMP_H */
